<a href="https://colab.research.google.com/github/irinakim21/Biblioteki-Python/blob/main/DZ7_matstat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [1]:
from math import sqrt

import numpy as np
import pandas as pd
import scipy.stats as stats

In [5]:
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
x

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [11]:
n = len(x)
n

10

In [12]:
B1 = (np.mean(x * y) - (np.mean(x) * np.mean(y))) / (np.mean(x**2) - np.mean(x) ** 2)
B1

2.620538882402765

In [15]:
A1 = np.mean(y) - B1 * np.mean(x)
A1

444.1773573243596

In [16]:
x = x.reshape((10,1)) # использование матричного метода
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [17]:
y = y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [19]:
B = np.dot(np.linalg.inv(np.dot(x.T,x)),x.T@y)
B

array([[5.88982042]])

In [26]:
x = np.hstack([np.ones((10,1)), x])
x

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [27]:
B = np.dot(np.linalg.inv(np.dot(x.T,x)),x.T@y)
B

array([[444.17735732],
       [  2.62053888]])

In [6]:
def mse_(B1, y=y, x=x, n=10):
  return np.sum(B1*x-y)**2/n

In [28]:
B1 = 0.1
alpha = 1e-6
alpha

1e-06

In [30]:
B = 0.1
for i in range(3000):
    B -= alpha*(2/n)*np.sum((B*x-y)*x)
    if i%500 == 0:
        print('Iteration: {i}, B={B}, mse={mse}'.format(i=i, B=B, mse=np.mean((B*x-y)**2)))

Iteration: 0, B=0.26094768, mse=513536.9986990768
Iteration: 500, B=5.940913730382343, mse=291290.05386730947
Iteration: 1000, B=5.940918592493807, mse=291290.05386714666
Iteration: 1500, B=5.940918592497952, mse=291290.05386714666
Iteration: 2000, B=5.940918592497952, mse=291290.05386714666
Iteration: 2500, B=5.940918592497952, mse=291290.05386714666


2.В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

Ответ 1. При неизвестной сигме/дисперсии генеральной совокупности используется критерий Стьюдента(таблица критических точек распределения Стьюдента).

2. Если сигма/дисперсия генеральной совокупности известна - используется Z критерий (таблица значений функции Лапласа)